### ISSUE TITLE
bcrypt for /etc/shadow hashes

### ISSUE THREAD

**Issue by michaelsbradleyjr** [coreos/manifest#38]
**Feature request:** support bcrypt hashes in `/etc/shadow`.

For conveniently generating random password and bcrypt-hash pairs on the command line (so as to use the latter member to populate, say, a `cloud-config` file), I've put together a little script: [passnhash.bash](https://gist.github.com/michaelsbradleyjr/dec5d69af50832166274).  There may be a better way, but it wasn't apparent to me what that was on my macbook pro.

However, after implementing that helper, I came to realize that CoreOS can't, at present, employ bcrypt hashing with respect to `/etc/shadow`.

**Comment by crawford** [comment]
This issue was moved to coreos/bugs#282
