### ISSUE TITLE
LDAP Support in CoreOS

### ISSUE THREAD

**Issue by Xe** [coreos/manifest#43]
I am sorry if this is not the correct place to file this issue. I have been investigating using CoreOS on a system where people have migrated to LDAP for authentication. How can I get CoreOS to support this?

**Comment by crawford** [comment]
github.com/coreos/bugs/issues is the preferred repo for these kinds of bugs.

As it exists today, LDAP requires PAM which requires modification in order to allow reading configuration from both /usr and /etc. If this is still an issue, please open a bug on the aforementioned repo.
