### ISSUE TITLE
Support enhanced networking in EC2 AMI

### ISSUE THREAD

**Issue by patrickbcullen** [coreos/manifest#52]
The CoreOS EC2 AMI does not currently support enhanced networking. See http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html. Can you add support to this to the AMI build process? You would also need to upgrade the the ixgbevf kernel module to a newer version based on the EC2 documentatin.

**Comment by adinapoli** [comment]
:+1: This would be awesome to have; any progress on this front?

Thanks!
Alfredo

**Comment by crawford** [comment]
This issue was moved to coreos/bugs#273
